version: 2.1

orbs:
  android: circleci/android@2.1.2

jobs:
  jacoco-report:
    parameters:
      system-image:
        type: string
        default: system-images;android-30;google_apis;x86
      avd-name:
        default: test
        type: string
    executor:
      name: android/android-machine
      tag: 2022.08.1
    steps:
      - checkout
      - android/create-avd:
          install: true
          avd-name: << parameters.avd-name>>
          system-image: << parameters.system-image >>
      - android/start-emulator:
          avd-name: << parameters.avd-name>>
          wait-for-emulator:
      - run:
          name: Generate test report
          command: |
            ./gradlew jacocoTestReport
      - store_artifacts:
          path: app/build/reports/jacoco/jacocoTestReport
  
  release-build:
    executor:
      name: android/android-docker
      tag: 2022.08.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release

workflows:
  build:
    jobs:
      - jacoco-report
      - release-build:
          requires:
            - jacoco-report