version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Assemble"
          command: "./gradlew assemble"

workflows:
  build-workflow:
    jobs:
      - build
