name: Java CI with Gradle

#on:
#  pull_request:
#    branches: [ "development" ]

on: [workflow_dispatch]

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Setup Gradle Cache
      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/development' && github.ref != 'MOEN-25997_ci_setup'}}
          gradle-home-cache-cleanup: true
      - name: Assemble project
        run: ./gradlew assemble --stacktrace
