name: Java CI with Gradle

#on:
#  pull_request:
#    branches: [ "development" ]

on: [workflow_dispatch]

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Setup Gradle Cache
      - uses: gradle/gradle-build-action@v2
      - name: Assemble Project
        run: ./gradlew assemble
  jvm-verification:
    needs: assemble
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - uses: gradle/gradle-build-action@v2
      - name: build
        run: ./gradlew build
      - name: Unit Test
        run: ./gradlew test
