name: Java CI with Gradle

#on:
#  pull_request:
#    branches: [ "development" ]

on: [workflow_dispatch]

jobs:
  pre-verification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ vars.gradleVersion }}
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/development'}}
          gradle-home-cache-cleanup: true
          arguments: assemble
  jvm-verification:
    needs: pre-verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: test
  android-verification:
    needs: pre-verification
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        api-level: [ 29 ]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/gradle-build-action@v2
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}
      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew connectedAndroidTest
      - name: Generating Code Coverage Report
        if: ${{ vars.codeCoverageEnabled == 'true' }}
        uses: ReactiveCircus/android-emulator-runner@v2.14.3
        with:
          api-level: ${{ vars.androidApiVersion }}
          script: ./gradlew jacocoTestReport
      - name: Uploading Code Coverage Report
        if: ${{ vars.codeCoverageEnabled == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: app/build/reports/jacoco/jacocoTestReport
