name: Android CI

on: [workflow_dispatch]

jobs:
  assemble-verification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Setup Gradle Cache
      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/development'}}
          gradle-home-cache-cleanup: true
      - name: Build project
        run: ./gradlew assemble
        
