
name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    
    - name: Unit Test with Android Emulator Runner
      uses: ReactiveCircus/android-emulator-runner@v2.14.3
      with: 
          api-level: 29
          script: ./gradlew jacocoTestReport
      
    - name: generate report
      uses: actions/upload-artifact@v3
      with:
        name: report 
        path: app/build/reports/jacoco/jacocoTestReport
            
    - name: Download Test Reports Folder
      uses: actions/download-artifact@v3
      with:
        name: report
        path: app/build/reports/jacoco/jacocoTestReport
        
    - name: Upload Test Report
      run:  bash <(curl -s https://codecov.io/bash) -f "app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml"

#     - name: Upload Test Report
#       uses: codecov/codecov-action@v3
#       with:
#           file: app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
      
