name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  assemble:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Assemble
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ vars.gradleVersion }}
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/development'' }}
          gradle-home-cache-cleanup: true
          dependency-graph: generate-and-submit
          arguments: |
            assemble
            ktlintcheck
            test
            
      - name: Run a build, generating the dependency graph snapshot which will be submitted
        run: ./gradlew build

      - name: Android Instrumentation Test
        uses: ReactiveCircus/android-emulator-runner@v2.14.3
        with:
          api-level: 33
          script: ./gradlew connectedAndroidTest
      
